### ISSUE TITLE
Focus around HourglassWidgetsTimeSpinner lingers

### ISSUE THREAD

**Issue by ChildishGiant** [sgpthomas/hourglass#191]
The accent at the top always stays with the first of the three clicked 

![image](https://user-images.githubusercontent.com/13716824/144274864-2ec87d33-19e8-4afa-90f5-b05e64334228.png)

**Comment by ryonakano** [comment]
Not sure if it's related but now the app is ported to Gtk 4 in the current `master` and this issue seems to be gone away:

![スクリーンショット 2023-01-07 00 58 29](https://user-images.githubusercontent.com/26003928/211049328-0324a1ee-e133-4083-8fb6-1149e5fc7f58.png)

Closing as fixed for now, but feel free to reopen if the issue persists with the Gtk 4 version of the app.
