### ISSUE TITLE
Feature Request: Power States at end of Timer

### ISSUE THREAD

**Issue by phillipstuerzl** [sgpthomas/hourglass#38]
Hey! 

Thanks for developing this little app. It's simple, but super useful. 
Don't want to put any pressure on you, but if you would have any motivation to do so, an extremely useful addition would be adding the ability to change the timer result from a timer tone, to automatically putting the computer to sleep, or shutting down, or rebooting, etc. 

This is a super basic thing, but surprisingly hard to do if you don't want to write a script or something yourself, and would be a great, and really useful feature!

As said before, if you don't feel the idea fits, or don't have the time or wish, no worries. Just thought i'd throw the concept out there! Thanks for this useful little accessory. 

Best wishes!

**Comment by sgpthomas** [comment]
I think this is a great idea! Hopefully I will get to this very soon. I hope to get back into the development of this app soon

**Comment by phillipstuerzl** [comment]
Awesome! Keep up the great work! Thanks!

**Comment by benavern** [comment]
Hi,

I have had the same need one day and coded something with languages I know : http://blog.caradeuc.info/zomnifer/

Never finished it but think it works, what do you think?

I was planning to write a vala app that does almost the same thing so that I'd have a project and learn native development

If you plan to add this feature, I'd be glad to help, and if some of you want to build a new app that does that, I'd be happy to participate :)

By the way, thanks for your great job, this app is very useful to me too ;)

See you

**Comment by sgpthomas** [comment]
Hi. Sorry for the late response. School and life has been keeping me busy. I'd be more than happy to accept help for this feature. If you start working on it, it's more than likely that I would pick up my work on this again haha. 

If you have any questions about the code, feel free to ask me.

**Comment by ryonakano** [comment]
Personally I'd like to keep this app just for alarm/timer/stopwatch, like the Clock app on iOS. You can use https://github.com/bcedu/ShutdownScheduler for scheduled shutdown.
